# Generated by Django 5.1.3 on 2024-12-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_full_name_profile_fullname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="fullname",
            new_name="fullName",
        ),
    ]
