# Generated by Django 5.1.1 on 2024-12-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="url",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default="default.png", upload_to="Product_images/"),
            preserve_default=False,
        ),
    ]
