# Generated by Django 5.1.1 on 2024-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
