# Generated by Django 5.1.1 on 2024-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_order_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
